// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../../mocks/outbound/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	outbound "github.com/redhajuanda/krangka/internal/core/port/outbound"
	repositories "github.com/redhajuanda/krangka/internal/core/port/outbound/repositories"
	qwery "github.com/redhajuanda/qwery"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DoInTransaction mocks base method.
func (m *MockRepository) DoInTransaction(ctx context.Context, fn func(outbound.Repository) (any, error)) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoInTransaction", ctx, fn)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoInTransaction indicates an expected call of DoInTransaction.
func (mr *MockRepositoryMockRecorder) DoInTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoInTransaction", reflect.TypeOf((*MockRepository)(nil).DoInTransaction), ctx, fn)
}

// GetNoteRepository mocks base method.
func (m *MockRepository) GetNoteRepository() repositories.Note {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteRepository")
	ret0, _ := ret[0].(repositories.Note)
	return ret0
}

// GetNoteRepository indicates an expected call of GetNoteRepository.
func (mr *MockRepositoryMockRecorder) GetNoteRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteRepository", reflect.TypeOf((*MockRepository)(nil).GetNoteRepository))
}

// PublishOutbox mocks base method.
func (m *MockRepository) PublishOutbox(ctx context.Context, target outbound.PublisherTarget, topic string, payload qwery.JSONMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOutbox", ctx, target, topic, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOutbox indicates an expected call of PublishOutbox.
func (mr *MockRepositoryMockRecorder) PublishOutbox(ctx, target, topic, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOutbox", reflect.TypeOf((*MockRepository)(nil).PublishOutbox), ctx, target, topic, payload)
}

// RetryOutbox mocks base method.
func (m *MockRepository) RetryOutbox(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryOutbox", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryOutbox indicates an expected call of RetryOutbox.
func (mr *MockRepositoryMockRecorder) RetryOutbox(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryOutbox", reflect.TypeOf((*MockRepository)(nil).RetryOutbox), ctx)
}
