// Code generated by MockGen. DO NOT EDIT.
// Source: dlock.go
//
// Generated by this command:
//
//	mockgen -source=dlock.go -destination=../../../mocks/outbound/mock_dlock.go -package=mocks_outbound
//

// Package mocks_outbound is a generated GoMock package.
package mocks_outbound

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDLocker is a mock of DLocker interface.
type MockDLocker struct {
	ctrl     *gomock.Controller
	recorder *MockDLockerMockRecorder
	isgomock struct{}
}

// MockDLockerMockRecorder is the mock recorder for MockDLocker.
type MockDLockerMockRecorder struct {
	mock *MockDLocker
}

// NewMockDLocker creates a new mock instance.
func NewMockDLocker(ctrl *gomock.Controller) *MockDLocker {
	mock := &MockDLocker{ctrl: ctrl}
	mock.recorder = &MockDLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDLocker) EXPECT() *MockDLockerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDLocker) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDLockerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDLocker)(nil).Close))
}

// Lock mocks base method.
func (m *MockDLocker) Lock(ctx context.Context, id string, ttl int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, id, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockDLockerMockRecorder) Lock(ctx, id, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockDLocker)(nil).Lock), ctx, id, ttl)
}

// TryLock mocks base method.
func (m *MockDLocker) TryLock(ctx context.Context, id string, ttl int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryLock", ctx, id, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// TryLock indicates an expected call of TryLock.
func (mr *MockDLockerMockRecorder) TryLock(ctx, id, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryLock", reflect.TypeOf((*MockDLocker)(nil).TryLock), ctx, id, ttl)
}

// Unlock mocks base method.
func (m *MockDLocker) Unlock(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockDLockerMockRecorder) Unlock(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockDLocker)(nil).Unlock), ctx, id)
}
