// Code generated by MockGen. DO NOT EDIT.
// Source: idempotency.go
//
// Generated by this command:
//
//	mockgen -source=idempotency.go -destination=../../../mocks/outbound/mock_idempotency.go -package=mocks_outbound
//

// Package mocks_outbound is a generated GoMock package.
package mocks_outbound

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIdempotency is a mock of Idempotency interface.
type MockIdempotency struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyMockRecorder
	isgomock struct{}
}

// MockIdempotencyMockRecorder is the mock recorder for MockIdempotency.
type MockIdempotencyMockRecorder struct {
	mock *MockIdempotency
}

// NewMockIdempotency creates a new mock instance.
func NewMockIdempotency(ctrl *gomock.Controller) *MockIdempotency {
	mock := &MockIdempotency{ctrl: ctrl}
	mock.recorder = &MockIdempotencyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotency) EXPECT() *MockIdempotencyMockRecorder {
	return m.recorder
}

// TryClaim mocks base method.
func (m *MockIdempotency) TryClaim(ctx context.Context, topic, messageID string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryClaim", ctx, topic, messageID, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryClaim indicates an expected call of TryClaim.
func (mr *MockIdempotencyMockRecorder) TryClaim(ctx, topic, messageID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryClaim", reflect.TypeOf((*MockIdempotency)(nil).TryClaim), ctx, topic, messageID, ttl)
}
