include:
  - project: platform/gitlab-ci
    file: /apps/gitlab-ssh-keys-v2.yml
  - project: platform/gitlab-ci
    file: /apps/ecr-multiarch-v2/push.yml
  - project: platform/gitlab-ci
    file: /apps/ecr/swag.yml
  - project: platform/gitlab-ci
    file: /apps/scan-secrets-ecr.yml
  # - project: platform/gitlab-ci
  #   file: /apps/ecr/sonarqube.yml
  - template: Security/SAST.gitlab-ci.yml

default:
  tags:
    - common

stages:
  - scan-secrets
  - test
  # # - sonarqube
  # - push
  # - swag


## START OVERRIDE
semgrep-sast:
  variables:
    KUBERNETES_NODE_SELECTOR_ARCH: "kubernetes.io/arch=amd64"
## END OVERRIDE

swag_sicepat:
  image: 537124960068.dkr.ecr.ap-southeast-1.amazonaws.com/platform/aws-cli-swaggo/production:go-1.24
  extends: .swag_sicepat
  only:
    refs:
      - staging


build-stag-amd64:
  stage: push
  extends:
    - .build-multiarch
  variables:
    KUBERNETES_NODE_SELECTOR_ARCH: "kubernetes.io/arch=amd64"
    ENV_BUILD: staging
    DOCKER_TAG: $CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    DOCKER_PLATFORM: linux/amd64
    DOCKERFILE_PATH: build/Dockerfile
    APP_NAME: $CI_PROJECT_NAME
    APP_PATH: "."
  only:
    refs:
      - staging

build-stag-arm64:
  stage: push
  extends:
    - .build-multiarch
  variables:
    ENV_BUILD: staging
    DOCKER_TAG: $CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    DOCKER_PLATFORM: linux/arm64
    DOCKERFILE_PATH: build/Dockerfile
    APP_NAME: $CI_PROJECT_NAME
    APP_PATH: "."
  only:
    refs:
      - staging

push-stag-multiarch:
  stage: push
  extends:
    - .push-multiarch
  variables:
    ENV_BUILD: staging
    DOCKER_TAG: $CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    DOCKER_PLATFORM: linux/amd64,linux/arm64
  needs:
    - job: build-stag-amd64
    - job: build-stag-arm64
  only:
    refs:
      - staging

build-prod-amd64:
  stage: push
  extends:
    - .build-multiarch
  variables:
    KUBERNETES_NODE_SELECTOR_ARCH: "kubernetes.io/arch=amd64"
    ENV_BUILD: production
    DOCKER_TAG: $CI_COMMIT_TAG
    DOCKER_PLATFORM: linux/amd64
    DOCKERFILE_PATH: build/Dockerfile
    APP_NAME: $CI_PROJECT_NAME
    APP_PATH: "."
  rules:
    - if: $CI_COMMIT_TAG

build-prod-arm64:
  stage: push
  extends:
    - .build-multiarch
  variables:
    ENV_BUILD: production
    DOCKER_TAG: $CI_COMMIT_TAG
    DOCKER_PLATFORM: linux/arm64
    DOCKERFILE_PATH: build/Dockerfile
    APP_NAME: $CI_PROJECT_NAME
    APP_PATH: "."
  rules:
    - if: $CI_COMMIT_TAG

push-prod-multiarch:
  stage: push
  extends:
    - .push-multiarch
  variables:
    ENV_BUILD: production
    DOCKER_TAG: $CI_COMMIT_TAG
    DOCKER_PLATFORM: linux/amd64,linux/arm64
  needs:
    - job: build-prod-amd64
    - job: build-prod-arm64
  rules:
    - if: $CI_COMMIT_TAG

golang-test-make:
  stage: test
  image: 537124960068.dkr.ecr.ap-southeast-1.amazonaws.com/docker-hub/library/golang:1.24
  extends:
    - .gitlab-ssh-keys
  script:
    - go mod download
    - go test -v -cover -short -count=1 -failfast ./... -coverprofile="coverage.out"
  artifacts:
    paths:
      - coverage.out
    expire_in: 1 hour
