// Code generated by MockGen. DO NOT EDIT.
// Source: note.go
//
// Generated by this command:
//
//	mockgen -source=note.go -destination=../../../mocks/inbound/mock_note.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pagination "github.com/redhajuanda/komon/pagination"
	domain "gitlab.sicepat.tech/pka/sds/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNote is a mock of Note interface.
type MockNote struct {
	ctrl     *gomock.Controller
	recorder *MockNoteMockRecorder
	isgomock struct{}
}

// MockNoteMockRecorder is the mock recorder for MockNote.
type MockNoteMockRecorder struct {
	mock *MockNote
}

// NewMockNote creates a new mock instance.
func NewMockNote(ctrl *gomock.Controller) *MockNote {
	mock := &MockNote{ctrl: ctrl}
	mock.recorder = &MockNoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNote) EXPECT() *MockNoteMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockNote) CreateNote(ctx context.Context, todo *domain.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteMockRecorder) CreateNote(ctx, todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNote)(nil).CreateNote), ctx, todo)
}

// DeleteNote mocks base method.
func (m *MockNote) DeleteNote(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteMockRecorder) DeleteNote(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNote)(nil).DeleteNote), ctx, id)
}

// GetNoteByID mocks base method.
func (m *MockNote) GetNoteByID(ctx context.Context, id string) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteByID", ctx, id)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteByID indicates an expected call of GetNoteByID.
func (mr *MockNoteMockRecorder) GetNoteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteByID", reflect.TypeOf((*MockNote)(nil).GetNoteByID), ctx, id)
}

// ListNote mocks base method.
func (m *MockNote) ListNote(ctx context.Context, req *domain.NoteFilter, arg2 *pagination.Pagination) (*[]domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNote", ctx, req, arg2)
	ret0, _ := ret[0].(*[]domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNote indicates an expected call of ListNote.
func (mr *MockNoteMockRecorder) ListNote(ctx, req, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNote", reflect.TypeOf((*MockNote)(nil).ListNote), ctx, req, arg2)
}

// UpdateNote mocks base method.
func (m *MockNote) UpdateNote(ctx context.Context, todo *domain.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNoteMockRecorder) UpdateNote(ctx, todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNote)(nil).UpdateNote), ctx, todo)
}